export { default as Calculator } from "./Calculator";
export { default as Bitacora } from "./Bitacora";
export { default as Zootecnico } from "./Zootecnico";
export { default as Especies } from "./Especies";
export { default as Fincas } from "./Fincas";
export { default as Parametros } from "./Parametros";
export { default as Formulas } from "./Formulas";
export { VeterinaryReportWizard } from "./veterinary";
export { default as MasterPage } from "./MasterPage";
export { default as Microbiologia } from "./Microbiologia";
export { default as Finanzas } from "./Finanzas";
export { default as Dashboard } from "./Dashboard";
export { default as Inventario } from "./Inventario";
export { default as Mapa } from "./Mapa";
export { default as Login } from "./Login";
